server:
  port: 8090

spring:
  datasource:
    ### MYSQL( DEV_85 )
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/dumsdb?useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useUnicode=true
    username: 123
    password: 123

  scheduler:
    # test 스케줄러
    test:
      # 사용여부
      use-yn: Y
      # test 스케줄 실행시간
      cron: "0 09 17 * * *"
